### List all messages
GET http://localhost:3000/messages


### Create a new message 下面要有一个空行
POST http://localhost:3000/messages
Content-Type: application/json

{
    "content":"second"
}

### Get a particular message
GET http://localhost:3000/messages/478